# Generated by Django 4.0 on 2021-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(db_column='baby_name', max_length=20)),
                ('baby_age', models.IntegerField(db_column='baby_age')),
                ('baby_birthdate', models.DateField(db_column='baby_birthdate')),
                ('parent_name', models.CharField(db_column='parent_name', max_length=20)),
                ('phone', models.CharField(db_column='phone', max_length=20)),
                ('address', models.CharField(db_column='address', max_length=200)),
                ('care_type', models.CharField(db_column='care_type', max_length=40)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(db_column='tutor', max_length=20)),
                ('time', models.CharField(db_column='time', max_length=20)),
                ('extend', models.CharField(db_column='extend', max_length=20)),
            ],
        ),
    ]
