# Generated by Django 4.0 on 2021-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0002_remove_application_baby_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.CharField(db_column='code', default='0', max_length=40),
        ),
    ]
