# Generated by Django 4.0 on 2021-12-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0003_application_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='code',
            field=models.CharField(db_column='code', max_length=40),
        ),
    ]
