# Generated by Django 4.0 on 2021-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0005_application_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='nation',
        ),
        migrations.AddField(
            model_name='application',
            name='language',
            field=models.CharField(db_column='language', default='한국어', max_length=40),
        ),
    ]
