# Generated by Django 4.0 on 2021-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0006_remove_application_nation_application_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='language',
            field=models.CharField(db_column='language', max_length=40),
        ),
    ]
