# Generated by Django 4.0 on 2021-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0007_alter_application_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='date',
            field=models.DateField(db_column='date', default='2021-01-01'),
        ),
        migrations.AlterModelTable(
            name='information',
            table='information',
        ),
    ]
