# Generated by Django 4.0 on 2021-12-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0008_information_date_alter_information_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(db_column='date'),
        ),
    ]
