# Generated by Django 4.0 on 2021-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0010_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_column='start')),
                ('end', models.DateField(db_column='end')),
                ('image', models.ImageField(default='default_image.jpg', upload_to='advertisement/')),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
    ]
