# Generated by Django 4.0 on 2022-02-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaho_app', '0011_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('on', models.BooleanField(db_column='on')),
            ],
            options={
                'db_table': 'section',
            },
        ),
    ]
